VICTIM:
  ARCHITECTURE: "resnet34"
  DATASET: "caltech256"
  DATASET_ROOT: "/mnt/disk1/sumdev/MSA_BTP/utils_train/data"
  WEIGHTS: "/mnt/disk1/sumdev/MSA_BTP/utils_train/Stealing_Task_1/caltech256-resnet34/checkpoint_new.pth"
  DEFENCE: "none" # # none, prada, adaptive-misinformation
  SHAPIRO_THRESHOLD: 0.985
  NUM_CLASSES: 256
  MSP_THRESHOLD: 0.5
  IS_API: False
THIEF:
  ARCHITECTURE: "resnet18"
  DATASET: "imagenet"
  DATASET_ROOT: "/mnt/disk1/sumdev/MSA_BTP/utils_train/data/Imagenet_full/Imagenet_2010_train/full_data"
  SUBSET: 1281167
  NUM_TRAIN: 1281167
  WEIGHTS: "default"
ACTIVE:
  BUDGET: 30000
  METHOD: "dfal"
  CYCLES: 10  
  DFAL_MAX_ITER: 2
TRAIN:
  OPTIMIZER: "sgd"
  LOSS_CRITERION: "cross_entropy_loss"
  BATCH_SIZE: 128
  WEIGHT_DECAY: 0.0001
  EPOCH: 100
  PATIENCE: 10
  LR: 0.01
  LOG_INTERVAL: 10
  BLACKBOX_TRAINING: False
  MILESTONES: [30,80]
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 3
DEVICE: "cuda:0"
OUT_DIR: "/mnt/disk1/sumdev/MSA_BTP/utils_train/Results/Stealing_Caltech256/resnet34_resnet18_dfal_nodef_wb"
