VICTIM:
  IS_API: True
  PLATFORM: 'hugging-face'
  DEFENCE: "none"
  MODEL_ID: 'facebook/convnext-base-384-22k-1k'
  # SHAPIRO_THRESHOLD: 0.994
THIEF:
  ARCHITECTURE: "resnet18"
  DATASET: "imagenet"
  DATASET_ROOT: "/mnt/disk1/sumdev/MSA_BTP/utils_train/data/Imagenet_full/Imagenet_2010_train/full_data"
  SUBSET: 1281167
  NUM_TRAIN: 1281167
  WEIGHTS: "default"
  NUM_CLASS: 5
ACTIVE:
  BUDGET: 30000
  METHOD: "kcenter"
  CYCLES: 10
  FEATURE: 'avgpool'
  METRIC: 'euclidean'
TRAIN:
  OPTIMIZER: "sgd"
  LOSS_CRITERION: "cross_entropy_loss"
  BATCH_SIZE: 64
  WEIGHT_DECAY: 0.0001
  EPOCH: 100
  PATIENCE: 10 
  LR: 0.01
  LOG_INTERVAL: 10
  BLACKBOX_TRAINING: True
  MILESTONES: [30,80]
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 1
DEVICE: "cuda:0"
OUT_DIR: "/mnt/disk1/sumdev/MSA_BTP/utils_train/Results/Stealing_HuggingfaceAPI/facebook_convnext/resnet18_kcenter_nodef_bb"
