VICTIM:
  DATASET: emnistletters
  ARCHITECTURE: vgg11_bn
  DATA_ROOT: 'dsfucbvcnuigvh usdy '
  WEIGHTS: default
THIEF:
  DATASET: imagenet
  ARCHITECTURE: vgg11
  DATA_ROOT: nybtverceww
  SUBSET: 20000
  NUM_TRAIN: 100000
  WEIGHTS: default
ACTIVE:
  BUDGET: 2029307.0
  METHOD: random
  CYCLES: 5.0
TRAIN:
  OPTIMIZER: adam
  LOSS_CRITERION: cross_entropy_loss
  BATCH_SIZE: 128
  WEIGHT_DECAY: 0.0001
  EPOCH: 10.0
  PATIENCE: 5
  LR: 0.001
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 2
DEVICE: cpu
LOG_DEST: /data/logs
OUT_DIR: /output/logs
