VICTIM:
  DATASET: cifar10
  ARCHITECTURE: resnet18
  DATA_ROOT: hj,mh,
  WEIGHTS: default
THIEF:
  DATASET: mnist
  ARCHITECTURE: resnet18
  DATA_ROOT: tfxnj
  SUBSET: 20000
  NUM_TRAIN: 100000
  WEIGHTS: default
ACTIVE:
  BUDGET: 4.0
  METHOD: random
  CYCLES: 7.0
TRAIN:
  OPTIMIZER: sgd
  LOSS_CRITERION: l1_loss
  BATCH_SIZE: 128
  WEIGHT_DECAY: 0.0001
  EPOCH: 9.0
  PATIENCE: 5
  LR: 0.001
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 2
DEVICE: cpu
LOG_DEST: /data/log
OUT_DIR: /output/
