VICTIM:
  DATASET: svhn
  ARCHITECTURE: resnet50
  DATA_ROOT: /home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/msa_toolbox/data/img
  WEIGHTS: default
  DEFENCE: prada
  SHAPIRO_THRESHOLD: 0.994
  NUM_CLASSES: 256
  MSP_THRESHOLD: 0.5
  IS_API: true
THIEF:
  DATASET: svhn
  ARCHITECTURE: resnet50
  DATA_ROOT: /home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/msa_toolbox/data/img
  SUBSET: 20000
  NUM_TRAIN: 100000
  WEIGHTS: default
ACTIVE:
  BUDGET: 10000.0
  METHOD: vaal
  CYCLES: 5.0
  FEATURE: avg_pool
  METRIC: euclidean
  DFAL_MAX_ITER: 1
  K: 1
  NUM_VAE_STEPS: 1
  NUM_ADV_STEPS: 1
  ADVERSARY_PARAM: 1
  BETA: 1
TRAIN:
  OPTIMIZER: adam
  LOSS_CRITERION: cross_entropy_loss
  BATCH_SIZE: '128'
  WEIGHT_DECAY: 0.0001
  EPOCH: 4.0
  PATIENCE: 5
  LR: 0.001
  BLACKBOX_TRAINING: true
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 2
DEVICE: cuda
OUT_DIR: /home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/Utils/SavedModels2
