artifacts: test
	python setup.py sdist bdist_wheel

prepforbuild:
	pip install --upgrade twine setuptools wheel

testrelease:
	twine upload --repository-url https://test.pypi.org/legacy/ dist/*

release: clean artifacts
	twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

# testing will be used later
testcov:
	pytest --cov-report html --cov=configuration tests/