VICTIM:
  ARCHITECTURE: "resnet18"
  DATASET: "svhn"
  DATA_ROOT: "/home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/msa_toolbox/data/img"
  WEIGHTS: "default"
THIEF:
  ARCHITECTURE: "resnet50"
  DATASET: "svhn"
  DATA_ROOT: "/home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/msa_toolbox/data/img"
  SUBSET: 20000
  NUM_TRAIN: 100000
  WEIGHTS: "default"
ACTIVE:
  BUDGET: 10000
  METHOD: "entropy"
  CYCLES: 5
TRAIN:
  OPTIMIZER: "adam"
  LOSS_CRITERION: "cross_entropy_loss"
  BATCH_SIZE: 128
  WEIGHT_DECAY: 0.0001
  EPOCH: 4
  PATIENCE: 5
  LR: 0.001
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 2
DEVICE: "cuda"
LOG_DEST: "/home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/Utils/Logs2"
OUT_DIR: "/home/vikram/akshitj/toolbox_btp/main_toolbox/MSA_BTP/Utils/SavedModels2"
