VICTIM:
  ARCHITECTURE: "resnet34"
  DATASET: "caltech256"
  DATASET_ROOT: "/mnt/disk1/sumdev/MSA_BTP/Utils/data"
  WEIGHTS: "/mnt/disk1/sumdev/MSA_BTP/Utils/Stealing_Task_1/caltech256-resnet34/checkpoint_new.pth"
  # WEIGHTS: "default"
THIEF:
  ARCHITECTURE: "resnet50"
  DATASET: "imagenet"
  DATASET_ROOT: "/mnt/disk1/sumdev/MSA_BTP/Utils/data/Imagenet_full/Imagenet_2010_train/full_data"
  SUBSET: 1281167
  NUM_TRAIN: 1281167
  WEIGHTS: "default"
ACTIVE:
  BUDGET: 30000
  METHOD: "entropy"
  CYCLES: 20
TRAIN:
  OPTIMIZER: "sgd"
  LOSS_CRITERION: "cross_entropy_loss"
  BATCH_SIZE: 64
  WEIGHT_DECAY: 0.0001
  EPOCH: 100
  PATIENCE: 10
  LR: 0.001
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 3
DEVICE: "cuda:0"
OUT_DIR: "/mnt/disk1/sumdev/MSA_BTP/Utils/Results/Stealing_Caltech256/resnet34_resnet50"
