VICTIM:
  ARCHITECTURE: "resnet18"
  DATASET: "mnist"
  WEIGHTS: "default"
THIEF:
  ARCHITECTURE: "resnet50"
  DATASET: "svhn"
  SUBSET: 20000
  NUM_TRAIN: 100000
  WEIGHTS: "default"
ACTIVE:
  BUDGET: 10000
  METHOD: "entropy"
  CYCLES: 5
TRAIN:
  OPTIMIZER: "adam"
  LOSS_CRITERION: "cross_entropy_loss"
  BATCH_SIZE: 128
  WEIGHT_DECAY: 0.0001
  EPOCH: 2
  PATIENCE: 5
  LR: 0.001
TRIALS: 1
DS_SEED: 123
NUM_WORKERS: 2
DEVICE: "cpu"
LOG_DEST: "C:/Users/khush/Desktop/ADS_MSA_BTP/Utils/Logs"
OUT_DIR: "C:/Users/khush/Desktop/ADS_MSA_BTP/Utils/SavedModels/Testing"
